package twitch.files.labels;

//LABEL LIST
public enum Labels {
	SUB_LATEST,
	SUB_COUNT_SESSION,
	SUB_COUNT_TOTAL,
	FOLLOW_LATEST,
	FOLLOW_COUNT_SESSION,
	FOLLOW_COUNT_TOTAL,
	BITS_LATEST,
	BITS_TOP_SESSION,
	BITS_TOP_ALL_TIME;
}
